# ============================================================================.
# Info #### 
# ============================================================================.
# The script calculates the normalised KL divergence by utilising posterior samples 
# generated by RStan for the KU model.
# 
# Zhilin Su
# zhilinsu1312@gmail.com / zxs203@student.bham.ac.uk / z.su.1@pgr.bham.ac.uk 
#
# Project: Zhilin's PhD project 2 - mPFC and social influence. 
# Last revision: 15 January 2025, Zhilin Su 

# ============================================================================.
# Preparation #### 
# ============================================================================.
# Clear all variables 
rm(list = ls())

# Load libraries and functions 
library(tidyverse)
library(rstan)
library(abind)
source("scripts/helper_functions/est_kld.R")
source("scripts/helper_functions/est_kld_ku.R")
source("scripts/helper_functions/helper_functions.R")

# ============================================================================.
# Set Populations & Initialisation #### 
# ============================================================================.
# 1 for healthy controls, 3 for mPFC lesions, 4 for lesion controls, 
pop <- 4

## Load data ---- 
load("data/sd_data_mpfc.RData")

if (pop == 1) { # healthy controls (hc)
	sd_data <- sd_hc
	other_k_mat <- k_hc
	incl_id <- readRDS("data/incl_id_hc.rds")
	
	ku_self_1 <- readRDS("data/stanfit/stanfit_ku0_hc_self_1.rds")
	ku_self_i <- readRDS("data/stanfit/stanfit_ku0_hc_self_i.rds")
	ku_self_p <- readRDS("data/stanfit/stanfit_ku0_hc_self_p.rds")
	
	ku_other_i <- readRDS("data/stanfit/stanfit_ku0_hc_other_i.rds")
	ku_other_p <- readRDS("data/stanfit/stanfit_ku0_hc_other_p.rds")

} else if (pop == 3) { # mPFC lesions 
	sd_data <- sd_mpfc
	other_k_mat <- k_mpfc
	incl_id <- readRDS("data/incl_id_mpfc.rds")
	
	ku_self_1 <- readRDS("data/stanfit/stanfit_ku0_mpfc_self_1.rds")
	ku_self_i <- readRDS("data/stanfit/stanfit_ku0_mpfc_self_i.rds")
	ku_self_p <- readRDS("data/stanfit/stanfit_ku0_mpfc_self_p.rds")
	
	ku_other_i <- readRDS("data/stanfit/stanfit_ku0_mpfc_other_i.rds")
	ku_other_p <- readRDS("data/stanfit/stanfit_ku0_mpfc_other_p.rds")

} else if (pop == 4) { # lesion controls (lc)
	sd_data <- sd_lc
	other_k_mat <- k_lc
	incl_id <- readRDS("data/incl_id_lc.rds")

	ku_self_1 <- readRDS("data/stanfit/stanfit_ku0_lc_self_1.rds")
	ku_self_i <- readRDS("data/stanfit/stanfit_ku0_lc_self_i.rds")
	ku_self_p <- readRDS("data/stanfit/stanfit_ku0_lc_self_p.rds")
	
	ku_other_i <- readRDS("data/stanfit/stanfit_ku0_lc_other_i.rds")
	ku_other_p <- readRDS("data/stanfit/stanfit_ku0_lc_other_p.rds")
}

## Set min_range based on the model
min_range <- -15

## Convert data type ----
other_k_tb <- other_k_mat |> 
	as_tibble() |> 
	mutate(id = as.numeric(id), 
				 other1_k = as.numeric(other1_k), 
				 other2_k = as.numeric(other2_k), 
				 other1_pref = as.factor(other1_pref), 
				 other2_pref = as.factor(other2_pref)) 

## Exclude participants ----
incl_condition <- sd_data[1, "id", ] %in% incl_id 
sd_data <- sd_data[,, incl_condition]
other_k_tb <- other_k_tb |> 
	filter(id %in% incl_id)

## Initialise data frames to store results ---- 
n_pt <- dim(sd_data)[3] # number of participants 

# For final results
col_names <- c("id", "self_1_km", "self_1_ku", 
							 "self_i_km", "self_i_ku", "self_p_km", "self_p_ku", 
							 "other_i_km", "other_i_ku", "other_p_km", "other_p_ku",
							 "kl_i", "kl_p", "norm_kl_i", "norm_kl_p")
result_mat <- matrix(nrow = n_pt, ncol = length(col_names))
colnames(result_mat) <- col_names
result_tb <- as_tibble(result_mat)
rm(result_mat)

## For self discount rates 
col_names <- c("id", "self_1_km", "self_1_ku", 
							 "self_i_km", "self_i_ku", "self_p_km", "self_p_ku")
self_k_mat <- matrix(nrow = n_pt, ncol = length(col_names))
colnames(self_k_mat) <- col_names
self_k_tb <- as_tibble(self_k_mat)
rm(self_k_mat)

## For KL divergence (intermediate)
col_names <- c("id", "kl_i", "kl_p", "norm_kl_i", "norm_kl_p")
kl_mat <- matrix(nrow = n_pt, ncol = length(col_names))
colnames(kl_mat) <- col_names 
kl_tb <- as_tibble(kl_mat)
rm(kl_mat)

# ============================================================================.
# Pre-process #### 
# ============================================================================.
# Extract participants' ID numbers
id_arr <- other_k_tb$id

result_tb$id <- id_arr 
self_k_tb$id <- id_arr
kl_tb$id <- id_arr

# Pre-process tibble other_k 
other_k_tb <- other_k_tb |> 
	mutate(other_i_km = if_else(other1_pref == "i", other1_k, other2_k),
				 other_p_km = if_else(other1_pref == "p", other1_k, other2_k)) |> 
	mutate(id = as.numeric(id),
				 other_i_km = as.numeric(other_i_km), 
				 other_p_km = as.numeric(other_p_km)) |> 
	dplyr::select(id, other_i_km, other_p_km, other1_pref, other2_pref) |> 
	mutate(other_i_ku = NA, 
				 other_p_ku = NA)

# ============================================================================.
# Main analysis #### 
# ============================================================================.
## Self block ---- 
self_1_km_summary <- summary(ku_self_1, "km")$summary
self_1_ku_summary <- summary(ku_self_1, "ku")$summary

self_i_km_summary <- summary(ku_self_i, "km")$summary
self_i_ku_summary <- summary(ku_self_i, "ku")$summary

self_p_km_summary <- summary(ku_self_p, "km")$summary
self_p_ku_summary <- summary(ku_self_p, "ku")$summary

## Other block ---- 
other_i_km_summary <- summary(ku_other_i, "km")$summary
other_i_ku_summary <- summary(ku_other_i, "ku")$summary

other_p_km_summary <- summary(ku_other_p, "km")$summary
other_p_ku_summary <- summary(ku_other_p, "ku")$summary

## Which function to use? ----
## 1 is based on posterior samples, 2 is based on mean and sd 
kl_function <- 2

for (i_id in 1:n_pt) {
	# Use mean for km and ku 
	self_k_tb$self_1_km[i_id] <- self_1_km_summary[i_id, "mean"]
	self_k_tb$self_1_ku[i_id] <- self_1_ku_summary[i_id, "mean"]
	
	self_k_tb$self_i_km[i_id] <- self_i_km_summary[i_id, "mean"]
	self_k_tb$self_i_ku[i_id] <- self_i_ku_summary[i_id, "mean"]
	
	self_k_tb$self_p_km[i_id] <- self_p_km_summary[i_id, "mean"]
	self_k_tb$self_p_ku[i_id] <- self_p_ku_summary[i_id, "mean"]
	
	other_k_tb$other_i_km[i_id] <- other_i_km_summary[i_id, "mean"]
	other_k_tb$other_i_ku[i_id] <- other_i_ku_summary[i_id, "mean"]
	
	other_k_tb$other_p_km[i_id] <- other_p_km_summary[i_id, "mean"]
	other_k_tb$other_p_ku[i_id] <- other_p_ku_summary[i_id, "mean"]
	
	# Extract posterior samples 
	cat(paste("Estimating KL divergence for the participant ", 
						id_arr[i_id], "\n", sep = ""))
	
	if (kl_function == 1) {
		sample_1 <- extract(ku_self_1)$km[, i_id]
		sample_i <- extract(ku_self_i)$km[, i_id]
		sample_p <- extract(ku_self_p)$km[, i_id]
		
		if (other_k_tb$other1_pref[i_id] == "i") {
			kl_tb$kl_i[i_id] <- est_kld(sample_i, sample_1, min_range = min_range)
			kl_tb$kl_p[i_id] <- est_kld(sample_p, sample_i, min_range = min_range)
			
		} else if (other_k_tb$other1_pref[i_id] == "p") {
			kl_tb$kl_p[i_id] <- est_kld(sample_p, sample_1, min_range = min_range)
			kl_tb$kl_i[i_id] <- est_kld(sample_i, sample_p, min_range = min_range)
		}
		
	} else if (kl_function == 2) {
		if (other_k_tb$other1_pref[i_id] == "i") {
			kl_tb$kl_i[i_id] <- est_kld_ku(self_k_tb$self_i_km[i_id], self_k_tb$self_i_ku[i_id], 
																		 self_k_tb$self_1_km[i_id], self_k_tb$self_1_ku[i_id], 
																		 min_range = min_range)
			kl_tb$kl_p[i_id] <- est_kld_ku(self_k_tb$self_p_km[i_id], self_k_tb$self_p_ku[i_id], 
																		 self_k_tb$self_i_km[i_id], self_k_tb$self_i_ku[i_id], 
																		 min_range = min_range)
			
		} else if (other_k_tb$other1_pref[i_id] == "p") {
			kl_tb$kl_p[i_id] <- est_kld_ku(self_k_tb$self_p_km[i_id], self_k_tb$self_p_ku[i_id], 
																		 self_k_tb$self_1_km[i_id], self_k_tb$self_1_ku[i_id], 
																		 min_range = min_range)
			kl_tb$kl_i[i_id] <- est_kld_ku(self_k_tb$self_i_km[i_id], self_k_tb$self_i_ku[i_id], 
																		 self_k_tb$self_p_km[i_id], self_k_tb$self_p_ku[i_id], 
																		 min_range = min_range)
		}
	}
}

# ============================================================================.
#### Signed KL divergence #### 
# ============================================================================.
# Function to test whether two numbers are of the same sign 
check_sign <- function(num1, num2) {
	if ((num1 > 0 && num2 > 0) || (num1 < 0 && num2 < 0)) {
		return(TRUE) 
	} else {
		return(FALSE)
	}
}

# Sign KL divergence 
## Positive values indicate a shift in pts' preferences towards the Other; 
## negative values indicate a shift in pts' preferences away from the Other 

for (i_id in 1:n_pt) {
	# For Impulsive Other 
	## Difference in k between baseline self and the self after seeing Other
	diff_ss_i <- self_k_tb[i_id, "self_1_km"] - self_k_tb[i_id, "self_i_km"]
	## Difference in k between baseline self and Other
	diff_so_i <- self_k_tb[i_id, "self_1_km"] - other_k_tb[i_id, "other_i_km"]
	
	if (check_sign(diff_ss_i, diff_so_i)) { # shift in the same direction 
		kl_tb[i_id, "norm_kl_i"] <- kl_tb[i_id, "kl_i"]
	} else {
		kl_tb[i_id, "norm_kl_i"] <- kl_tb[i_id, "kl_i"] * (-1) 
	}
	
	# For Patient Other 
	## Difference in k between baseline self and the self after seeing Other
	diff_ss_p <- self_k_tb[i_id, "self_1_km"] - self_k_tb[i_id, "self_p_km"]
	## Difference in k between baseline self and Other
	diff_so_p <- self_k_tb[i_id, "self_1_km"] - other_k_tb[i_id, "other_p_km"]
	
	if (check_sign(diff_ss_p, diff_so_p)) { # shift in the same direction 
		kl_tb[i_id, "norm_kl_p"] <- kl_tb[i_id, "kl_p"]
	} else {
		kl_tb[i_id, "norm_kl_p"] <- kl_tb[i_id, "kl_p"] * (-1) 
	}
}

# Handle exceptions: when pts had no Others of different preferences 
for (i_id in 1:n_pt) {
	diff_i <- self_k_tb[i_id, "self_1_km"] - other_k_tb[i_id, "other_i_km"]
	diff_p <- self_k_tb[i_id, "self_1_km"] - other_k_tb[i_id, "other_p_km"]
	
	if (check_sign(diff_i, diff_p) && diff_i > 0) { # no Impulsive Other
		# Data were analysed for the other agent with the greatest distance between 
		# the participant’s own discount rate, and the model discount rate.
		if (abs(diff_i) > abs(diff_p)) {
			kl_tb[i_id, "norm_kl_p"] <- kl_tb[i_id, "norm_kl_i"]
			kl_tb[i_id, "norm_kl_i"] <- NA
		} else if (abs(diff_i) < abs(diff_p)) {
			kl_tb[i_id, "norm_kl_i"] <- NA
		}
		
	} else if (check_sign(diff_i, diff_p) && diff_i < 0) { # no Patient Other
		if (abs(diff_i) > abs(diff_p)) {
			kl_tb[i_id, "norm_kl_p"] <- NA
		} else if (abs(diff_i) < abs(diff_p)) {
			kl_tb[i_id, "norm_kl_i"] <- kl_tb[i_id, "norm_kl_p"]
			kl_tb[i_id, "norm_kl_p"] <- NA
		}
	}
}

# ============================================================================.
#### Save results #### 
# ============================================================================.
result_tb[, c("self_1_km", "self_1_ku", "self_i_km", 
							"self_i_ku", "self_p_km", "self_p_ku")] <- 
	self_k_tb[, c("self_1_km", "self_1_ku", "self_i_km", 
								"self_i_ku", "self_p_km", "self_p_ku")]

result_tb[, c("other_i_km", "other_i_ku", "other_p_km", "other_p_ku")] <- 
	other_k_tb[, c("other_i_km", "other_i_ku", "other_p_km", "other_p_ku")]

result_tb[, c("kl_i", "kl_p", "norm_kl_i", "norm_kl_p")] <- 
	kl_tb[, c("kl_i", "kl_p", "norm_kl_i", "norm_kl_p")]

if (pop == 1) {
	file <- "data/ku0_kld_hc.RData"
} else if (pop == 3) {
	file <- "data/ku0_kld_mpfc.RData"
} else if (pop == 4) {
	file <- "data/ku0_kld_lc.RData"
}

save(result_tb, file = file)